# general settings
name: LKMN_pieapp_x4_3_half
model_type: SRModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10
# python basicsr/train.py -opt options/train/train_LKMN_x4.yml --auto_resume
# dataset and data loader settings
datasets:
  train:
    name: Pexel
    type: PairedImageDataset
    #dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub
    #dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic/X2_sub
    # (for lmdb)
    dataroot_gt: /data/github/LKMN/basicsr/train_pairs_x4.pkl
    dataroot_lq:
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      #type: lmdb

    gt_size: 256,256    # 48*48 LR input
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 10
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: Pexel4K
    type: PairedImageDataset
    dataroot_gt: /data/github/LKMN/basicsr/val_pairs_x4.pkl
    dataroot_lq:
    gt_size: 256,256    # 48*48 LR input
    io_backend:
      type: disk



# network structures
network_g:
  type: LKMN
  in_channels: 3
  channels: 36
  out_channels: 3
  upscale: 4
  num_block: 8
  large_kernel: 31
  split_group: 4

half: true

# path
path:
  pretrain_network_g: /data/github/LKMN/experiments/LKMN_pieapp_x4_1.5/models/net_g_13000.pth
  strict_load_g: true
  resume_state: ~


# training settings
train:
 ema_decay: 0.999
 optim_g:
   type: SGD
   lr: !!float 1e-8
   momentum: 0.9
   nesterov: true
   #betas: [0.98, 0.92, 0.99]
   weight_decay: !!float 1e-5
   foreach: true

 scheduler:
   type: CosineAnnealingRestartLR
   periods: [1000000]
   restart_weights: [1]
   eta_min: !!float 1e-9


 total_iter: 1000000
 warmup_iter: -1  # no warm up

 # losses
 pixel_opt:
   type: CharbonnierLoss
   loss_weight: 1
   reduction: mean
   eps: !!float 2e-2

 edge_aware_opt:
   type: Edge_Aware_L1Loss
   loss_weight: !!float 0
   reduction: mean

 tv_opt:
   type: WeightedTVLoss
   loss_weight: !!float 0
   reduction: mean

 fft_opt:
   type: FFTLoss
   loss_weight: 0
   reduction: mean

 perceptual_opt:
   type: PerceptualLoss
   layer_weights:
     'conv5_4': 1  # before relu
   vgg_type: vgg19
   use_input_norm: true
   range_norm: false
   perceptual_weight: !!float 0
   style_weight: 0
   criterion: l1


# validation settings
val:
 val_freq: !!float 1e3
 save_img: true
 self_ensemble_testing: false

 metrics:
   PSNR: # metric name, can be arbitrary
     type: calculate_psnr
     crop_border: 4
     test_y_channel: true
     better: higher
   SSIM:
     type: calculate_ssim
     crop_border: 4
     test_y_channel: true
     better: higher

# logging settings
logger:
 print_freq: 100
 save_checkpoint_freq: !!float 1e3
 use_tb_logger: true
 wandb:
   project: ~
   resume_id: ~

# dist training settings
dist_params:
 backend: nccl
 port: 29500
